// Mirrors app/static/transition-picker.js's TRANSITIONS list — same ids,
// labels and preview GIFs, ported into the canvas's own React setup.
export const TRANSITIONS = [
  { id: "none", label: "Без перехода", preview: null },
  { id: "fade", label: "Плавное перетекание" },
  { id: "wipeleft", label: "Шторка влево" },
  { id: "wiperight", label: "Шторка вправо" },
  { id: "wipeup", label: "Шторка вверх" },
  { id: "wipedown", label: "Шторка вниз" },
  { id: "slideleft", label: "Сдвиг влево" },
  { id: "slideright", label: "Сдвиг вправо" },
  { id: "slideup", label: "Сдвиг вверх" },
  { id: "slidedown", label: "Сдвиг вниз" },
  { id: "circlecrop", label: "Круг (обрезка)" },
  { id: "rectcrop", label: "Прямоугольник (обрезка)" },
  { id: "distance", label: "Дистанция" },
  { id: "fadeblack", label: "Через чёрный" },
  { id: "fadewhite", label: "Через белый" },
  { id: "radial", label: "Радиальный" },
  { id: "smoothleft", label: "Плавно влево" },
  { id: "smoothright", label: "Плавно вправо" },
  { id: "smoothup", label: "Плавно вверх" },
  { id: "smoothdown", label: "Плавно вниз" },
  { id: "circleopen", label: "Круг (открытие)" },
  { id: "circleclose", label: "Круг (закрытие)" },
  { id: "vertopen", label: "Открытие по вертикали" },
  { id: "vertclose", label: "Закрытие по вертикали" },
  { id: "horzopen", label: "Открытие по горизонтали" },
  { id: "horzclose", label: "Закрытие по горизонтали" },
  { id: "dissolve", label: "Растворение" },
  { id: "diagtl", label: "Диагональ ↖" },
  { id: "diagtr", label: "Диагональ ↗" },
  { id: "diagbl", label: "Диагональ ↙" },
  { id: "diagbr", label: "Диагональ ↘" },
  { id: "hlslice", label: "Полосы слева" },
  { id: "hrslice", label: "Полосы справа" },
  { id: "vuslice", label: "Полосы снизу" },
  { id: "vdslice", label: "Полосы сверху" },
  { id: "fadegrays", label: "Через чёрно-белое" },
  { id: "wipetl", label: "Шторка из угла ↖" },
  { id: "wipetr", label: "Шторка из угла ↗" },
  { id: "wipebl", label: "Шторка из угла ↙" },
  { id: "wipebr", label: "Шторка из угла ↘" },
  { id: "squeezeh", label: "Сжатие по горизонтали" },
  { id: "squeezev", label: "Сжатие по вертикали" },
].map((t) => ({ ...t, preview: t.preview === null ? null : `${t.id}.gif` }));
